version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mysql:
    image: 'bitnami/mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ci
      - MYSQL_USER=ci
      - MYSQL_PASSWORD=123
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  coordinator:
    image: lightflus/coordinator
    hostname: coordinator
    ports:
      - '8791:8791'
    environment:
      RUST_LOG: INFO
      WORKER_1: worker
    depends_on:
      - worker
  worker:
    image: lightflus/worker
    hostname: worker
    ports:
      - '8792:8792'
    environment:
      RUST_LOG: INFO
  apiserver:
    image: lightflus/apiserver
    environment:
      RUST_LOG: INFO
      LIGHTFLUS_COORDINATOR_URI: http://coordinator:8791
    ports:
      - "8080:8080"
    depends_on:
      - coordinator
