version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=f8-O0IuOq#O9T52r
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: f8-O0IuOq#O9T52r
  tableflow-coordinator:
    build:
      context: .
      dockerfile: docker/coordinator/Dockerfile
    ports:
      - "8091:8091"
    environment:
      MONGO_HOST: mongo
      MONGO_USERNAME: root
      MONGO_PASSWORD: f8-O0IuOq#O9T52r
      CLUSTER_1: tableflow-worker
      CONNECTOR_PROXY: tableflow-connector:10899
      KAFKA_BROKERS: kafka:9002
    depends_on:
      - tableflow-connector
      - tableflow-worker
  tableflow-worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    ports:
      - "8090:8090"
  tableflow-connector:
    build:
      context: .
      dockerfile: docker/connector/Dockerfile
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - "10899:10899"
  tableflow-qe:
    image: tableflow-qe:latest
    ports:
      - "9090:9090"
    environment:
      KAFKA_BROKERS_1: kafka:9092
      REDIS_HOST: redis
      STORE_TYPE: MinIO
      STORE_NAME: minio
      STORE_ENDPOINT: minio:9000
      STORE_ACCESS_ID: LTAI5tEgJF8gPbzZUHUQyzYd
      STORE_ACCESS_SECRET: 6ab2at3WQ8JkBZaOxoBvf03zlV7n0t
      STORE_BUCKET: tableflow