version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  coordinator:
    image: lightflus/coordinator:latest
    build:
      context: .
      dockerfile: docker/coordinator/Dockerfile
    ports:
      - "18091:18091"
    environment:
      RUST_LOG: INFO
      WORKER_NODE_1: worker-1
    depends_on:
      - worker
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/lightflus/runtime/tools/healthcheck",
          "-TARGET localhost:8791",
          "-METHOD /proto.CoordinatorApi/Probe",
          "-SERVICE 0",
          "-PROBE 1"
        ]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 10s
  worker:
    image: lightflus/worker:latest
    hostname: worker-1
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    environment:
      RUST_LOG: INFO
    ports:
      - "18090:18090"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/lightflus/runtime/tools/healthcheck",
          "-TARGET localhost:18090",
          "-METHOD /proto.TaskWorkerApi/Probe",
          "-SERVICE 1",
          "-PROBE 0"
        ]
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
  apiserver:
    image: lightflus/apiserver:latest
    hostname: apiserver-1
    build:
      context: .
      dockerfile: docker/apiserver/Dockerfile
    environment:
      RUST_LOG: INFO
    ports:
      - "18090:18090"
    depends_on:
      - coordinator
