version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  coordinator:
    image: tableflow/runtime/coordinator:latest
    build:
      context: .
      dockerfile: docker/coordinator/Dockerfile
    ports:
      - "18091:18091"
    environment:
      MONGO_HOST: mongo
      MONGO_USERNAME: root
      MONGO_PASSWORD: f8-O0IuOq#O9T52r
      WORKER_NODE_1: tableflow-worker
      CONNECTOR_PROXY: tableflow-connector:10899
      KAFKA_BROKERS: kafka:9002
    depends_on:
      - worker
  worker:
    image: tableflow/runtime/worker:latest
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    ports:
      - "18090:18090"