[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt", "sync", "macros"] }
serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
futures-executor = "0.3"
connector = { path = "../connector" }
common = { path = "../common" }
dataflow-api = { path = "../dataflow-api", features = ["coordinator", "worker"] }

grpcio = "0.10.0"
protobuf = "2.0"
env_logger = "0.9.0"

[dependencies.mongodb]
version = "2.1.0"
default-features = false
features = ["sync"]