name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check Coordinator
        run: cargo install --path .
      - name: Check Worker
        run: cargo install --path dataflow-worker/
      - name: Run common lib tests
        run: cargo test --manifest-path common/Cargo.toml
      - name: Run dataflow tests
        run: cargo test --manifest-path dataflow-test/Cargo.toml
      - name: Build coordinator image
        run: docker build . --file Dockerfile-coordinator --tag dataflow-coordinator:$(date +%s)
      - name: Build worker image
        run: docker build . --file Dockerfile-worker --tag dataflow-worker:$(date +%s)
