name: tablflow CI

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]
  release:
    types: [ published ]

jobs:

  test_and_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run common lib tests
        run: cargo test --manifest-path common/Cargo.toml
      - name: Run dataflow tests
        run: cargo test --manifest-path dataflow-test/Cargo.toml
      - name: Check coordinator
        run: cargo build
      - name: Check worker
        run: cargo build --manifest-path dataflow-worker/Cargo.toml

  build_docker_image:

    if: ${{ github.event_name == 'release' }}

    needs: [test_and_build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Coordinator
        run: cargo install --path .
      - name: Install Worker
        run: cargo install --path dataflow-worker/
      - name: Build coordinator image
        run: docker build . --file docker/coordinator/Dockerfile --tag markmakemate/dataflow-coordinator:${{ github.event.release.tag_name }}
      - name: Build worker image
        run: docker build . --file docker/worker/Dockerfile --tag markmakemate/dataflow-worker:${{ github.event.release.tag_name }}
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish worker docker image
        run: docker push markmakemate/dataflow-worker:${{ github.event.release.tag_name }}
      - name: Publish coordinator docker image
        run: docker push markmakemate/dataflow-coordinator:${{ github.event.release.tag_name }}
