name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Coordinator
      run: cargo check
    - name: Check Worker
      run: cargo check --manifest-path dataflow-worker/Cargo.toml
    - name: Run common lib tests
      run: cargo test --manifest-path common/Cargo.toml
    - name: Run dataflow tests
      run: cargo test --manifest-path dataflow-test/Cargo.toml
