name: tablflow-runtime cicd

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]
  release:
    types: [ published ]

jobs:

  test_and_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run proto build
        run: cargo check --manifest-path src/proto/Cargo.toml
      - name: Run common lib tests
        run: cargo test --manifest-path src/common/Cargo.toml
      - name: Run dataflow tests
        run: cargo test --manifest-path src/stream/Cargo.toml
      - name: Check Coordinator
        run: cargo check --manifest-path src/coordinator/Cargo.toml
      - name: Check Worker
        run: cargo check --manifest-path src/worker/Cargo.toml

  build_docker_image:

    if: ${{ github.event_name == 'release' }}

    needs: [ test_and_build ]

    runs-on: ubuntu-latest

    steps:
      - name: Build coordinator image
        run: docker build . --file docker/coordinator/Dockerfile --tag markmakemate/tableflow/runtime/coordinator:${{ github.event.release.tag_name }}
      - name: Build worker image
        run: docker build . --file docker/worker/Dockerfile --tag markmakemate/tableflow/runtime/worker:${{ github.event.release.tag_name }}
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish worker docker image
        run: docker push markmakemate/tableflow/runtime/worker:${{ github.event.release.tag_name }}
      - name: Publish coordinator docker image
        run: docker push markmakemate/tableflow/runtime/coordinator:${{ github.event.release.tag_name }}